
package br.com.trabalho1.view;

import br.com.trabalho1.controller.AlunoController;
import br.com.trabalho1.model.Aluno;
import br.com.trabalho1.model.DiaDaSemanaEnum;
import br.com.trabalho1.model.Disciplina;
import br.com.trabalho1.model.Horario;
import br.com.trabalho1.model.exceptions.MatriculaInexistenteException;
import br.com.trabalho1.model.exceptions.MatriculaVaziaException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class TelaAluno extends Tela{

    /**
     * Creates new form TelaGradeHorariosFrame
     */
    public TelaAluno(AlunoController alunoController) {
        this.alunoController = alunoController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matriculaLabel = new javax.swing.JLabel();
        matriculaTextField = new javax.swing.JTextField();
        pesquisaButton = new javax.swing.JButton();
        separador = new javax.swing.JSeparator();
        scroll = new javax.swing.JScrollPane();
        gradeHorariosJbable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        matriculaLabel.setText("Matricula");

        pesquisaButton.setText("Pesquisar");
        pesquisaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisaButtonMouseClicked(evt);
            }
        });

        gradeHorariosJbable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"07:30", null, null, null, null, null, null},
                {"08:20", null, null, null, null, null, null},
                {"09:10", null, null, null, null, null, null},
                {"10:10", null, null, null, null, null, null},
                {"11:00", null, null, null, null, null, null},
                {"13:30", null, null, null, null, null, null},
                {"14:20", null, null, null, null, null, null},
                {"15:10", null, null, null, null, null, null},
                {"16:20", null, null, null, null, null, null},
                {"17:10", null, null, null, null, null, null},
                {"18:30", null, null, null, null, null, null},
                {"19:20", null, null, null, null, null, null},
                {"20:20", null, null, null, null, null, null},
                {"21:10", null, null, null, null, null, null}
            },
            new String [] {
                "Horarios", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sabado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gradeHorariosJbable.setAlignmentX(1.0F);
        gradeHorariosJbable.setAlignmentY(1.0F);
        scroll.setViewportView(gradeHorariosJbable);
        if (gradeHorariosJbable.getColumnModel().getColumnCount() > 0) {
            gradeHorariosJbable.getColumnModel().getColumn(1).setResizable(false);
            gradeHorariosJbable.getColumnModel().getColumn(2).setResizable(false);
            gradeHorariosJbable.getColumnModel().getColumn(3).setResizable(false);
            gradeHorariosJbable.getColumnModel().getColumn(4).setResizable(false);
            gradeHorariosJbable.getColumnModel().getColumn(5).setResizable(false);
            gradeHorariosJbable.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(matriculaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(matriculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pesquisaButton)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matriculaLabel)
                    .addComponent(matriculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisaButton))
                .addGap(18, 18, 18)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaButtonMouseClicked
        try {
            Aluno aluno = alunoController.buscar(matriculaTextField.getText());         
            for(Disciplina disciplina : aluno.getDisciplinas()){
                DefaultTableModel model = (DefaultTableModel) gradeHorariosJbable.getModel();
                List<Horario> horarios = disciplina.getHorarios();
                for(Horario horario: horarios){
                    DiaDaSemanaEnum diaSemana = horario.getDiaDaSemana();
                    model.setValueAt(valorCelula(disciplina), horario.getHora(), diaSemana.getCodigo()+1);
                }                               
            }
            
        } catch(MatriculaInexistenteException | MatriculaVaziaException e){
            super.error(e.getMessage());
        }
    }//GEN-LAST:event_pesquisaButtonMouseClicked

    private String valorCelula(Disciplina disciplina){
        return disciplina.getNome() + " / " + disciplina.getCodigo();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable gradeHorariosJbable;
    private javax.swing.JLabel matriculaLabel;
    private javax.swing.JTextField matriculaTextField;
    private javax.swing.JButton pesquisaButton;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
    private final AlunoController alunoController; 

}

