
package br.com.trabalho1.view;

import br.com.trabalho1.controller.AlunoController;
import br.com.trabalho1.model.Aluno;
import br.com.trabalho1.model.DiaDaSemanaEnum;
import br.com.trabalho1.model.Disciplina;
import br.com.trabalho1.model.Horario;
import br.com.trabalho1.model.exceptions.MatriculaInexistenteException;
import br.com.trabalho1.model.exceptions.MatriculaVaziaException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class TelaAluno extends Tela{

    /**
     * Creates new form TelaGradeHorariosFrame
     */
    public TelaAluno(AlunoController alunoController) {
        this.alunoController = alunoController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matriculaLabel = new javax.swing.JLabel();
        matriculaTextField = new javax.swing.JTextField();
        pesquisaButton = new javax.swing.JButton();
        separador = new javax.swing.JSeparator();
        scroll = new javax.swing.JScrollPane();
        gradeHorariosJbable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextNomeAluno = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        limparButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        matriculaLabel.setText("Matricula");

        pesquisaButton.setText("Pesquisar");
        pesquisaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisaButtonMouseClicked(evt);
            }
        });

        gradeHorariosJbable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"07:30", null, null, null, null, null, null},
                {"08:20", null, null, null, null, null, null},
                {"09:10", null, null, null, null, null, null},
                {"10:10", null, null, null, null, null, null},
                {"11:00", null, null, null, null, null, null},
                {"13:30", null, null, null, null, null, null},
                {"14:20", null, null, null, null, null, null},
                {"15:10", null, null, null, null, null, null},
                {"16:20", null, null, null, null, null, null},
                {"17:10", null, null, null, null, null, null},
                {"18:30", null, null, null, null, null, null},
                {"19:20", null, null, null, null, null, null},
                {"20:20", null, null, null, null, null, null},
                {"21:10", null, null, null, null, null, null}
            },
            new String [] {
                "Horarios", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sabado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gradeHorariosJbable.setAlignmentX(1.0F);
        gradeHorariosJbable.setAlignmentY(1.0F);
        scroll.setViewportView(gradeHorariosJbable);

        jLabel1.setText("Nome:");

        jTextNomeAluno.setEnabled(false);
        jScrollPane1.setViewportView(jTextNomeAluno);

        jLabel2.setText("Horarios");

        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(matriculaLabel)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(matriculaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(pesquisaButton)
                                .addGap(18, 18, 18)
                                .addComponent(limparButton)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(33, 33, 33))
                    .addComponent(jLabel2)
                    .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matriculaLabel)
                    .addComponent(matriculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisaButton)
                    .addComponent(limparButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaButtonMouseClicked
        try {
            Aluno aluno = alunoController.buscar(matriculaTextField.getText());     
            this.jTextNomeAluno.setText(aluno.getNome());
            for(Disciplina disciplina : aluno.getDisciplinas()){
                DefaultTableModel model = (DefaultTableModel) gradeHorariosJbable.getModel();
                List<Horario> horarios = disciplina.getHorarios();
                for(Horario horario: horarios){
                    DiaDaSemanaEnum diaSemana = horario.getDiaDaSemana();
                    model.setValueAt(valorCelula(disciplina)+horario, horario.getHora(), diaSemana.getCodigo()+1);
                }                               
            }
            
        } catch(MatriculaInexistenteException | MatriculaVaziaException e){
            super.error(e.getMessage());
        }
    }//GEN-LAST:event_pesquisaButtonMouseClicked

    private void limparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparButtonActionPerformed
        this.jTextNomeAluno.setText("");
        this.matriculaTextField.setText("");
        DefaultTableModel model = (DefaultTableModel) gradeHorariosJbable.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            for (int j = 1; j < model.getColumnCount(); j++) {
                model.setValueAt("", i, j);
            }
        }
    }//GEN-LAST:event_limparButtonActionPerformed

    private String valorCelula(Disciplina disciplina){
        return disciplina.getNome() + " / " + disciplina.getCodigo() + " ";
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable gradeHorariosJbable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextNomeAluno;
    private javax.swing.JButton limparButton;
    private javax.swing.JLabel matriculaLabel;
    private javax.swing.JTextField matriculaTextField;
    private javax.swing.JButton pesquisaButton;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
    private final AlunoController alunoController; 

}

